# Generated by Django 4.0.2 on 2022-02-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadeFederativa', models.CharField(max_length=60)),
                ('abreviacao', models.CharField(max_length=2)),
                ('capital', models.CharField(max_length=60)),
                ('area', models.DecimalField(decimal_places=2, max_digits=19)),
                ('populacao', models.BigIntegerField()),
                ('pib', models.BigIntegerField()),
            ],
        ),
    ]
